Completed Hibernate-01
Vedroid/jv-hibernate-cinema pull request #1
Opened 2021-01-26 14:21 UTC by Vedroid

2021-01-26 14:51 UTC, Max-Pochepets approved these changes
👍

2021-01-26 14:51 UTC, Max-Pochepets commented on src/main/resources/hibernate.cfg.xml
> +        <!-- currentSchema=cinema& -->
no need

2021-01-26 16:31 UTC, Sofasmile requested changes
good job)

2021-01-26 16:31 UTC, Sofasmile commented on src/main/java/ua/vedroid/cinema/dao/impl/MovieDaoImpl.java
> +            throw new DataProcessingException("Can`t insert Movie entity", e);
```suggestion
            throw new DataProcessingException("Can`t insert Movie entity " + movie, e);
```

2021-01-27 07:15 UTC, Sofasmile approved these changes

2021-01-27 14:20 UTC, merged