Completed spring07
Vedroid/jv-hibernate-cinema pull request #10
Opened 2021-02-18 13:49 UTC by Vedroid

2021-02-18 14:57 UTC, YuraBondarenko approved these changes

2021-02-18 14:57 UTC, YuraBondarenko commented on src/main/java/ua/vedroid/cinema/lib/FieldMatch.java
> +    }
you can delete it

2021-02-19 07:58 UTC, boroda4436 requested changes

2021-02-19 07:58 UTC, boroda4436 commented on src/main/java/ua/vedroid/cinema/lib/EmailValidator.java
> +        return email != null && email.matches("\\w+@[a-z]+\\.[a-z]+");
let's make the regex as a constant

2021-02-19 07:58 UTC, boroda4436 commented on src/main/java/ua/vedroid/cinema/model/dto/UserRegistrationDto.java
> +    @Size(min = PASS_MIN_LENGTH, max = PASS_MAX_LENGTH, message = PASS_MESSAGE)
it's ok to write numbers right here
```suggestion
    @Size(min = 4, max = 16, message = "Password size must be between 4 and 16")
```

2021-02-19 09:31 UTC, boroda4436 approved these changes

2021-02-19 09:36 UTC, merged